// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type Response struct {
	Code    int    `json:"code"`
	Data    string `json:"data"`
	Message string `json:"message"`
}

type UserInfo struct {
	UserName string `json:"user_name"`
	Addr     string `json:"addr"`
	Id       uint   `json:"id"`
}

type UserInfoResponse struct {
	Code    int      `json:"code"`
	Data    UserInfo `json:"user_info"`
	Message string   `json:"message"`
}
