// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type UserInfoResponse struct {
	UserName string `json:"user_name"`
	Addr     string `json:"addr"`
	Id       uint   `json:"id"`
}
